#############################################################################
# Makefile for building: Release/RateCheck.app/Contents/MacOS/RateCheck
# Generated by qmake (3.1) (Qt 6.4.0)
# Project:  RateCheck.pro
# Template: app
# Command: /Users/mathyossarkiss/Qt5/6.4.0/macos/bin/qmake -o Makefile RateCheck.pro -spec macx-clang CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DLINUX -DGCC -DFoundation_EXPORTS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wall -Wextra $(DEFINES)
INCPATH       = -I. -Isupport/poco/include -Isupport -I../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers -I../../Qt5/6.4.0/macos/lib/QtGui.framework/Headers -I../../Qt5/6.4.0/macos/lib/QtCore.framework/Headers -I. -I../../Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I../../Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I../../Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt5/6.4.0/macos/mkspecs/macx-clang -F/Users/mathyossarkiss/Qt5/6.4.0/macos/lib
QMAKE         = /Users/mathyossarkiss/Qt5/6.4.0/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/mathyossarkiss/Qt5/6.4.0/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/mathyossarkiss/Qt5/6.4.0/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RateCheck1.0.0
DISTDIR = /Users/mathyossarkiss/Personal/rateCheck/Release/RateCheck1.0.0
LINK          = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacosx-version-min=10.14 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/mathyossarkiss/Qt5/6.4.0/macos/lib
LIBS          = $(SUBLIBS) -F/Users/mathyossarkiss/Qt5/6.4.0/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = Release/

####### Files

SOURCES       = appManager.cpp \
		main.cpp \
		mainwindow.cpp \
		support/start_stop_watch.cpp \
		support/benchmark.cpp \
		support/file_manager.cpp moc_mainwindow.cpp
OBJECTS       = Release/appManager.o \
		Release/main.o \
		Release/mainwindow.o \
		Release/start_stop_watch.o \
		Release/benchmark.o \
		Release/file_manager.o \
		Release/moc_mainwindow.o
DIST          = ../../Qt5/6.4.0/macos/mkspecs/features/spec_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/device_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/common/unix.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/macx.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/sanitize.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/gcc-base.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/clang.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/clang-mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/qconfig.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/features/qt_functions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qt_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt5/6.4.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5/6.4.0/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/sdk.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/toolchain.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/default_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resolve_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/default_post.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/default_post.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qtquickcompiler.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/mac.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/warn_on.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qt.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resources_functions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resources.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/moc.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/unix/opengl.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/uic.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/unix/thread.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qmake_use.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/file_copies.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/rez.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/testcase_targets.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/exceptions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/yacc.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/lex.prf \
		RateCheck.pro appManager.h \
		mainwindow.h \
		support/benchmark.h \
		support/start_stop_watch.h \
		support/file_manager.h appManager.cpp \
		main.cpp \
		mainwindow.cpp \
		support/start_stop_watch.cpp \
		support/benchmark.cpp \
		support/file_manager.cpp
QMAKE_TARGET  = RateCheck
DESTDIR       = Release/
TARGET        = Release/RateCheck.app/Contents/MacOS/RateCheck

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 12.3
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer
EXPORT__QMAKE_STASH_ = /Users/mathyossarkiss/Personal/rateCheck/.qmake.stash
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/mathyossarkiss/Personal/rateCheck/RateCheck.pro


include /Users/mathyossarkiss/Qt5/6.4.0/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

Release/RateCheck.app/Contents/MacOS/RateCheck: ui_mainwindow.h $(OBJECTS)  
	@test -d Release/RateCheck.app/Contents/MacOS/ || mkdir -p Release/RateCheck.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RateCheck.pro ../../Qt5/6.4.0/macos/mkspecs/macx-clang/qmake.conf ../../Qt5/6.4.0/macos/mkspecs/features/spec_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/device_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/common/unix.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/macx.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/sanitize.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/gcc-base.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/gcc-base-mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/clang.conf \
		../../Qt5/6.4.0/macos/mkspecs/common/clang-mac.conf \
		../../Qt5/6.4.0/macos/mkspecs/qconfig.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5/6.4.0/macos/mkspecs/features/qt_functions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qt_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/macx-clang/qmake.conf \
		../../Qt5/6.4.0/macos/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5/6.4.0/macos/mkspecs/features/exclusive_builds.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/sdk.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/toolchain.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/toolchain.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/default_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/default_pre.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resolve_config.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/default_post.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/default_post.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/objective_c.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qtquickcompiler.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/mac.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/warn_on.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qt.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resources_functions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/resources.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/moc.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/unix/opengl.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/uic.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/unix/thread.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/qmake_use.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/file_copies.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/rez.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/testcase_targets.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/exceptions.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/yacc.prf \
		../../Qt5/6.4.0/macos/mkspecs/features/lex.prf \
		RateCheck.pro \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../../Qt5/6.4.0/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../../Qt5/6.4.0/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile RateCheck.pro -spec macx-clang CONFIG+=qtquickcompiler
../../Qt5/6.4.0/macos/mkspecs/features/spec_pre.prf:
../../Qt5/6.4.0/macos/mkspecs/features/device_config.prf:
../../Qt5/6.4.0/macos/mkspecs/common/unix.conf:
../../Qt5/6.4.0/macos/mkspecs/common/mac.conf:
../../Qt5/6.4.0/macos/mkspecs/common/macx.conf:
../../Qt5/6.4.0/macos/mkspecs/common/sanitize.conf:
../../Qt5/6.4.0/macos/mkspecs/common/gcc-base.conf:
../../Qt5/6.4.0/macos/mkspecs/common/gcc-base-mac.conf:
../../Qt5/6.4.0/macos/mkspecs/common/clang.conf:
../../Qt5/6.4.0/macos/mkspecs/common/clang-mac.conf:
../../Qt5/6.4.0/macos/mkspecs/qconfig.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_freetype.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_ext_libpng.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_chartsqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core5compat_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_httpserver_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_jsonrpc_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_languageserver_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediaquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdf_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_png_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3d_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3deffects_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quicktimeline_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_scxmlqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sensorsquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_shadertools_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_spatialaudio_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachine_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_statemachineqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_webviewquick_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml.pri:
../../Qt5/6.4.0/macos/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5/6.4.0/macos/mkspecs/features/qt_functions.prf:
../../Qt5/6.4.0/macos/mkspecs/features/qt_config.prf:
../../Qt5/6.4.0/macos/mkspecs/macx-clang/qmake.conf:
../../Qt5/6.4.0/macos/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5/6.4.0/macos/mkspecs/features/exclusive_builds.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/sdk.prf:
../../Qt5/6.4.0/macos/mkspecs/features/toolchain.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/toolchain.prf:
../../Qt5/6.4.0/macos/mkspecs/features/default_pre.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/default_pre.prf:
../../Qt5/6.4.0/macos/mkspecs/features/resolve_config.prf:
../../Qt5/6.4.0/macos/mkspecs/features/default_post.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/default_post.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/objective_c.prf:
../../Qt5/6.4.0/macos/mkspecs/features/qtquickcompiler.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/mac.prf:
../../Qt5/6.4.0/macos/mkspecs/features/warn_on.prf:
../../Qt5/6.4.0/macos/mkspecs/features/qt.prf:
../../Qt5/6.4.0/macos/mkspecs/features/resources_functions.prf:
../../Qt5/6.4.0/macos/mkspecs/features/resources.prf:
../../Qt5/6.4.0/macos/mkspecs/features/moc.prf:
../../Qt5/6.4.0/macos/mkspecs/features/unix/opengl.prf:
../../Qt5/6.4.0/macos/mkspecs/features/uic.prf:
../../Qt5/6.4.0/macos/mkspecs/features/unix/thread.prf:
../../Qt5/6.4.0/macos/mkspecs/features/qmake_use.prf:
../../Qt5/6.4.0/macos/mkspecs/features/file_copies.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/rez.prf:
../../Qt5/6.4.0/macos/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5/6.4.0/macos/mkspecs/features/testcase_targets.prf:
../../Qt5/6.4.0/macos/mkspecs/features/exceptions.prf:
../../Qt5/6.4.0/macos/mkspecs/features/yacc.prf:
../../Qt5/6.4.0/macos/mkspecs/features/lex.prf:
RateCheck.pro:
../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../../Qt5/6.4.0/macos/lib/QtGui.framework/Resources/QtGui.prl:
../../Qt5/6.4.0/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile RateCheck.pro -spec macx-clang CONFIG+=qtquickcompiler

qmake_all: FORCE

Release/RateCheck.app/Contents/PkgInfo: 
	@test -d Release/RateCheck.app/Contents || mkdir -p Release/RateCheck.app/Contents
	@$(DEL_FILE) Release/RateCheck.app/Contents/PkgInfo
	@echo "APPL????" > Release/RateCheck.app/Contents/PkgInfo
Release/RateCheck.app/Contents/Resources/empty.lproj: 
	@test -d Release/RateCheck.app/Contents/Resources || mkdir -p Release/RateCheck.app/Contents/Resources
	@touch Release/RateCheck.app/Contents/Resources/empty.lproj
	
Release/RateCheck.app/Contents/Info.plist: 
	@test -d Release/RateCheck.app/Contents || mkdir -p Release/RateCheck.app/Contents
	@$(DEL_FILE) Release/RateCheck.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.integratedsw.hexcalc.RateCheck,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.integratedsw.hexcalc.RateCheck,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.14,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,RateCheck,g" -e "s,@LIBRARY@,RateCheck,g" -e "s,\$${EXECUTABLE_NAME},RateCheck,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Qt5/6.4.0/macos/mkspecs/macx-clang/Info.plist.app >Release/RateCheck.app/Contents/Info.plist

all: Makefile \
		Release/RateCheck.app/Contents/PkgInfo \
		Release/RateCheck.app/Contents/Resources/empty.lproj \
		Release/RateCheck.app/Contents/Info.plist Release/RateCheck.app/Contents/MacOS/RateCheck

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents appManager.h mainwindow.h support/benchmark.h support/start_stop_watch.h support/file_manager.h $(DISTDIR)/
	$(COPY_FILE) --parents appManager.cpp main.cpp mainwindow.cpp support/start_stop_watch.cpp support/benchmark.cpp support/file_manager.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Release/RateCheck.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=qtquickcompiler

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		appManager.h \
		../../Qt5/6.4.0/macos/libexec/moc
	/Users/mathyossarkiss/Qt5/6.4.0/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=14 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/mathyossarkiss/Qt5/6.4.0/macos/mkspecs/macx-clang -I/Users/mathyossarkiss/Personal/rateCheck -I/Users/mathyossarkiss/Personal/rateCheck/support/poco/include -I/Users/mathyossarkiss/Personal/rateCheck/support -I/Users/mathyossarkiss/Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers -I/Users/mathyossarkiss/Qt5/6.4.0/macos/lib/QtGui.framework/Headers -I/Users/mathyossarkiss/Qt5/6.4.0/macos/lib/QtCore.framework/Headers -I/Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1 -I/Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include -I/Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include -I/Users/mathyossarkiss/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/mathyossarkiss/Qt5/6.4.0/macos/lib mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt5/6.4.0/macos/libexec/uic
	/Users/mathyossarkiss/Qt5/6.4.0/macos/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Release/appManager.o: appManager.cpp appManager.h \
		support/start_stop_watch.h \
		support/benchmark.h \
		support/file_manager.h \
		../../Qt5/6.4.0/macos/lib/QtCore.framework/Headers/QString \
		../../Qt5/6.4.0/macos/lib/QtCore.framework/Headers/qstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/appManager.o appManager.cpp

Release/main.o: main.cpp mainwindow.h \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		appManager.h \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/main.o main.cpp

Release/mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		appManager.h \
		ui_mainwindow.h \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/QFileDialog \
		../../Qt5/6.4.0/macos/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../Qt5/6.4.0/macos/lib/QtCore.framework/Headers/QThread \
		../../Qt5/6.4.0/macos/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/mainwindow.o mainwindow.cpp

Release/start_stop_watch.o: support/start_stop_watch.cpp support/start_stop_watch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/start_stop_watch.o support/start_stop_watch.cpp

Release/benchmark.o: support/benchmark.cpp support/benchmark.h \
		support/start_stop_watch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/benchmark.o support/benchmark.cpp

Release/file_manager.o: support/file_manager.cpp support/file_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/file_manager.o support/file_manager.cpp

Release/moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Release/moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

