name: CentOS
on: 
  push:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/centos.yml'
  pull_request:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/centos.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [centos-8]
        qt_ver: [6.2.2]
        qt_arch: [gcc_64]
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: CentOS install GL library
        run: sudo yum install -y mesa-libGL-devel
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build centos
        run: |
          qmake
          make
      # artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}_${{matrix.qt_ver}}.zip
          path: Release/${{ matrix.os }}_${{matrix.qt_ver}}
      # tag Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release/${{ matrix.os }}_${{matrix.qt_ver}}.zip
          asset_name: ${{ matrix.os }}_${{matrix.qt_ver}}.zip
          tag: ${{ github.ref }}
          overwrite: true
