name: Ubuntu
on: 
  push:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/ubuntu.yml'
  pull_request:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/ubuntu.yml' 
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04,ubuntu-20.04]
        qt_ver: [6.2.2]
        qt_arch: [gcc_64]
        exclude: 
          # Qt6.2.2 need GLIBC_2.28, ubuntu 18.04 have not.
          - os: ubuntu-18.04
            qt_ver: 6.2.2
            qt_arch: gcc_64
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          qmake
          make
      # artifacts          
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}.zip
          path: Release/${{ env.targetName }}.run
      # tag Release
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Release/${{ env.targetName }}.zip
          asset_name: ${{ env.targetName }}_${{ matrix.os }}_${{ matrix.qt_ver }}.zip
          tag: ${{ github.ref }}
          overwrite: true
