name: Windows MinGW
on: 
  push:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/windows-mingw.yml'
  pull_request:
    paths:
      - '**'
      - '*.pro'
      - 'src/**'
      - '.github/workflows/windows-mingw.yml' 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Install Qt Creator and MinGW
      - name: Install Qt Creator and MinGW
        run: |
          choco install qt-creator --version 6.3.2 -y
          choco install mingw -y

      # Add Qt and MinGW to the PATH
      - name: Set up Qt and MinGW
        run: |
          echo "::set-env name=PATH::${{ env.PATH }};C:/Qt/6.3.2/mingw81_64/bin;C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin"

      # Build the project using qmake and MinGW
      - name: Build the project
        run: |
          cd RateCheck
          qmake RateCheck.pro
          mingw32-make

      # Deploy the application executable using qwindeploy
      - name: Deploy the application executable
        run: |
          cd RateCheck/release
          qwindeploy -qmake=C:/Qt/6.3.2/mingw81_64/bin/qmake.exe -release -exe=rateCheck.exe -no-translations

      # Upload the release archive to the tagged release folder in the repository
      - name: Upload the release archive
        uses: actions/upload-release-asset@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: archive
          file: rateCheck-release.tar.gz
