name: Windows-MinGW 
on: 
  push:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/windows-mingw.yml'
  pull_request:
    paths:
      - '**'
      - '*.pro'
      - 'support/**'
      - '.github/workflows/windows-mingw.yml' 

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt Creator
        run: |
          Invoke-WebRequest -Uri "https://download.qt.io/official_releases/qtcreator/8.0/8.0.2/qt-creator-opensource-windows-x86_64-8.0.2.exe" -OutFile qt-creator.exe
      - name: Generate makefile with qmake
        run: |
          "C:/Qt/6.4/mingw82_64/bin/qmake.exe" rateCheck.pro
      - name: Build project with make
        run: |
          make
      - name: Deploy executable with windeployqt
        run: |
          "C:/Qt/6.4/mingw82_64/bin/windeployqt.exe" --qmldir "path/to/qml" rateCheck.exe
      - name: Zip executable and deployment files
        run: |
          zip -r rateCheck_win.zip rateCheck.exe Qt* platforms
          mv rateCheck_win.zip rateCheck_${GITHUB_REF#refs/tags/}.zip
      - name: Deploy to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: rateCheck_Win_${GITHUB_REF#refs/tags/}.zip
          asset_name: rateCheck_Win_${GITHUB_REF#refs/tags/}.zip
          asset_content_type: application/zip
